
id = "helicoprion"
name = "Helicoprion"
description = "A proof of concept anticheat for Webfishing"
version = "0.0.1"
homepage = "https://github.com/yeeterlol/helicoprion"
author = "yeeter"

icon = "icon.png"
readme = "README.md"

[project]
csharp = "./WebfishingSampleMod/WebfishingSampleMod.csproj"

[[dependencies]]
thunderstore_version = "NotNet-GDWeave-2.0.14"
